version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Running tests..."
      - python -m unittest discover -s tests
      - echo "Creating deployment package..."
      - zip -r lambda-deployment.zip .
  post_build:
    commands:
      - echo "Build completed"
artifacts:
  files:
    - lambda-deployment.zip