version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - apt-get update -y
      - apt-get install -y python3-venv
      - python3 -m ensurepip --upgrade
      - python3 -m venv venv
      - source venv/bin/activate
      - pip install --upgrade pip
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Running tests..."
      - python -m unittest discover -s tests
      - echo "Creating lambda-deployment.zip..."
      - zip -r lambda-deployment.zip lambda_function.py
  post_build:
    commands:
      - echo "Build completed"
artifacts:
  files:
    - lambda-deployment.zip